version: "3.9"

services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dbTask
    #volumes:
      #- postgres_data:/var/lib/postgresql/data

  dbAdmin:
    image: dpage/pgadmin4:9.8
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

  # Descomentar para crear un volumen local
  #volumes:
    #postgres_data